version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: sourcetrace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sourcetrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sourcetrace_pg_data:/var/lib/postgresql/data

volumes:
  sourcetrace_pg_data:

